name: Auto Assign

on:
  pull_request:

jobs:
  assign:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      repository-projects: read

    steps:
      - run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }}
