name: Auto Assign

on:
  pull_request:

jobs:
  assign:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      repository-projects: read

    steps:
      - name: add assignee
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }}
