name: Auto Assign

on:
  pull_request:
    types: [ opend ]

jobs:
  assign-author:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
