name: Auto Assign

on:
  pull_request:

jobs:
  assign-author:
    permissions:
      pull-requests: write
      repository-projects: read
    runs-on: ubuntu-latest
    steps:
      - run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }}
