name: Build And Run 2

on:
  push:
  pull_request:

env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

#      - name: Build and push Docker images
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          push: false
#          tags: myapp:latest
#
#      - name: Run docker-compose
#        run: docker-compose up --build -d
#
#      - name: Wait for services to be healthy
#        run: |
#          while ! docker-compose exec postgres pg_isready -U myuser; do
#            sleep 1
#          done
